
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: qbo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pg-backup:
    image: postgres:15
    depends_on:
      - postgres
    environment:
      - PGPASSWORD=postgres
    volumes:
      - ./pg_backups:/backups  
    entrypoint: >
      bash -c '
        mkdir -p /backups &&
        while true; do
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          pg_dump -h postgres -U postgres -d qbo > /backups/backup_$TIMESTAMP.sql
          echo "Backup saved: backup_$TIMESTAMP.sql"
          sleep 3600  # every hour
        done
      '

  api-service:
    build: ./api-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - QBO_SANDBOX_BASE=${QBO_SANDBOX_BASE}
      - START_UP_PERIOD=${START_UP_PERIOD}
      - USE_UI=${USE_UI}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./api-service:/app
    restart: always

  crawler-service:
    build: ./crawler-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - QBO_SANDBOX_BASE=${QBO_SANDBOX_BASE}
      - START_UP_PERIOD=${START_UP_PERIOD}
    # depends_on:
    #   - postgres
    volumes:
      - ./crawler-service:/app
    restart: always
  ui:
    build: ./ui
    ports:
      - "3000:8080"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api-service
    restart: always

volumes:
  postgres-data:
